name: g4music
base: core24
adopt-info: gapless
grade: stable
confinement: strict
compression: lzo
platforms:
  amd64:
  arm64:

slots:
  g4music:
    interface: dbus
    bus: session
    name: com.github.neithern.g4music
  mpris:
    name: Gapless

apps:
  gapless:
    command: usr/bin/g4music
    extensions: [gnome]
    plugs:
      - home
      - audio-playback
      - network
      - network-status
      - network-bind
      - unity7
      - screen-inhibit-control
      - removable-media
    slots:
      - mpris
    common-id: com.github.neithern.g4music
    desktop: usr/share/applications/com.github.neithern.g4music.desktop

parts:
  gapless:
    source: https://gitlab.gnome.org/neithern/g4music.git
    source-depth: 1
    source-tag: 'v4.3.1'
    plugin: meson
    parse-info: [usr/share/metainfo/com.github.neithern.g4music.metainfo.xml]
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
    build-packages:
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - cmake
    override-pull: |
      craftctl default
      sed -e 's|Icon=@app_id@|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/com.github.neithern.g4music.svg|' -i data/app.desktop.in
    prime:
      - -usr/share/metainfo
